#via http://stackoverflow.com/a/11030209
TXTDIR=dist
HTMLS=$(wildcard dist/*.html)
MDS=$(patsubst %.html,%.markdown, $(HTMLS))

.PHONY : all

all : $(MDS)

#$(TXTDIR) :
#	mkdir $(TXTDIR)

$(TXTDIR)/%.markdown : $(TXTDIR)/%.html $(TXTDIR)
	pandoc -f html -t markdown -s $< -o $@
